"""criandologin

Revision ID: f4421fd9a4d8
Revises: 8b44312cdd22
Create Date: 2024-05-13 21:23:04.624592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4421fd9a4d8'
down_revision = '8b44312cdd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('datadenascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('fk_tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_usuario')
    # ### end Alembic commands ###
